kind: PersistentVolume
apiVersion: v1
metadata:
  name: auth-postgres-pv-volume
  labels:
    type: local
    app: authorization
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data/authorization"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: auth-postgres-pv-claim
  labels:
    app: authorization
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi